# Site
name: "Vandersonpc"
title: "Vanderson Web Site"
description: "My Personal Website about Electronics and Technology"
logo: 'images/vpc_logo.png'
favicon: 'images/page_favicon.png'
baseurl: "https://www.vandersonpc.com"
url: ""
google_analytics: 'G-74FFZNQ8KP'
#disqus:
#mailchimp-list: #
include: ["_pages"]
permalink: /:title/

# Authors
# authors:
#   sal:
#     name: Sal
#     display_name: Sal
#     gravatar: e56154546cf4be74e393c62d1ae9f9d4
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net
#     twitter: https://twitter.com/wowthemesnet
#     description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and envi. You are currently previewing Jekyll template demo."
#   Jon:
#     name: John
#     display_name: John
#     avatar: 'assets/images/avatar.png'
#     gravatar: b1cc14991db7a456fcd761680bbc8f81
#     email: wowthemesnet@gmail.com
#     web: https://www.wowthemes.net
#     twitter: https://twitter.com/wowthemesnet
#     description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

#-------------------------------
# Author Settings
author:
  name: Vanderson
  display_name: Vanderson Carvalho
  image: /images/van.png
  say-hello: Hello 👋🏼, I’m <strong>Vanderson Carvalho</strong>
  bio: <br>I do <b>Electrical</b> & <b>Electronic</b> things and sometimes write about it here.<br>I'm Electrical/Electronic Engineer living in UK 🇬🇧 who loves to create and build things.🛠🤓.<br>Currently doing Electrical and Electronic Design @ <a href="http://www.bakerhughes.com">Baker Hughes</a>.
  avatar: 'assets/images/avatar.png'
  gravatar: b1cc14991db7a456fcd761680bbc8f81
  email: 'vandersonpc@gmail.com'
  twitter: https://twitter.com/pc_vanderson
  facebook: https://facebook.com/vanderson.pimenta
  github: https://github.com/vandersonpc
  curriculum: /files/cv_vanderson_en.pdf

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
